### ISSUE TITLE
Not creating accounts

### ISSUE THREAD

**Issue by PranavMahesh1** [novskey/PalletTown#13]
I'm trying to create 5 accounts, but when they were created, they didn't export to the file.
Screenshot: http://prntscr.com/ee79jk

Log:
http://pastebin.com/GCfzR8VF
If you could help, that would be great. Thanks!

**Comment by Memurame** [comment]
I have the same error.

**Comment by parislarkins** [comment]
Looking at the log you an see the accounts failed to create, hence why they weren't added to the file. Looking at the errors, stale element looks like you were doing manual captcha and you clicked the submit button. PalletTown does it automatically so I you click it, it can't ind it hence the error

**Comment by PranavMahesh1** [comment]
I did do manual captcha, it does it automatically so I can just click submit?

**Comment by parislarkins** [comment]
Once you manually solve the captcha you don't need to click submit, it will click submit for you automatically once the captcha is solved

**Comment by PranavMahesh1** [comment]
Thanks, it works!
