### ISSUE TITLE
Failed to create users

### ISSUE THREAD

**Issue by claublog** [novskey/PalletTown#18]
I think PTC has disabled plusmail and thus, using it with hotmail, gmail or any other domain accounts with "+" and random strings won't work anymore. Can anyone confirm that?

**Comment by altor90** [comment]
Hello,

I have the same problem! And do not know how to solve it...

Please help!

**Comment by parislarkins** [comment]
Are you using hotmail @altor90? PTC patched hotmail + trick recently. Try zoho or googlemail

**Comment by altor90** [comment]
Like in another thread - yes. Thank you again :)
