### ISSUE TITLE
[RESPONSE_VALIDATOR]: Username already in use

### ISSUE THREAD

**Issue by ghost** [novskey/PalletTown#9]
Captcha manually filled, received the confirmation email (which was forwarded to Gmail for auto verifying), but still got the error as in the title and no account:password was dumped to the output file.

Edit: I tried several different usernames, and even the auto generated ones didn't work.

**Comment by parislarkins** [comment]
Could you post the full log when this happens? I believe it's a problem when the account is created but doesn't redirect after creation, so it tries to create, sees the page is still the sign up page, and assumes something went wrong. Please let me know what the log says and ill investigate this :)

**Comment by ghost** [comment]
Sure!

The content of pallettown.log is:

```
[Main Thread]:  initializing..
[Main Thread]: Attempting to create user <name>:<pwd>. Opening browser...
[Main Thread]: Proxy type: 
[Main Thread]: No 2captcha key
[Main Thread]: trying to execute workaround script
[Main Thread]: done executing workaround script, submitting dob
[Main Thread]: dob submitted
[Main Thread]: Step 2: Entering account details
[Main Thread]: https://club.pokemon.com/us/pokemon-trainer-club/parents/sign-up
[Main Thread]: https://club.pokemon.com/us/pokemon-trainer-club/sign-up/
[Main Thread]: You did not pass a 2captcha key. Please solve the captcha manually.
[Main Thread]: Waiting on captcha
[Main Thread]: Captcha successful. Sleeping for 1 second...
[Main Thread]: trying to submit
[Main Thread]: submitted
[Main Thread]: trying to validate response
[RESPONSE_VALIDATOR]: https://club.pokemon.com/us/pokemon-trainer-club/parents/sign-up
[RESPONSE_VALIDATOR]: Username already in use
[Main Thread]: Failed to create user: <name>...
[Main Thread]: threw failed to create user exception, terminate
```

(name and password removed for privacy reasons)

Also, I keep getting a geckodriver.log:

```
1487756381623	geckodriver	INFO	Listening on 127.0.0.1:43368
1487756382624	mozprofile::profile	INFO	Using profile path /tmp/rust_mozprofile.NmY3jUdOXfHX
1487756382627	geckodriver::marionette	INFO	Starting browser /usr/bin/firefox
1487756382633	geckodriver::marionette	INFO	Connecting to Marionette on localhost:46544
1487756383957	Marionette	INFO	Listening on port 46544

(firefox:7117): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'g_type_parent (interface_type) == G_TYPE_INTERFACE' failed`

(firefox:7117): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'g_type_parent (interface_type) == G_TYPE_INTERFACE' failed

(firefox:7117): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'g_type_parent (interface_type) == G_TYPE_INTERFACE' failed
1487756393556	Marionette	WARN	Using deprecated data structure for setting timeouts

(firefox:7117): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'g_type_parent (interface_type) == G_TYPE_INTERFACE' failed

(firefox:7117): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'g_type_parent (interface_type) == G_TYPE_INTERFACE' failed

(firefox:7117): GLib-GObject-CRITICAL **: g_type_add_interface_static: assertion 'g_type_parent (interface_type) == G_TYPE_INTERFACE' failed

(firefox:7117): GLib-GObject-WARNING **: /build/glib2.0-prJhLS/glib2.0-2.48.2/./gobject/gsignal.c:3486: signal name 'selection_changed' is invalid for instance '0x7f5a2dece470' of type 'MaiAtkType139'

(firefox:7117): GLib-GObject-WARNING **: /build/glib2.0-prJhLS/glib2.0-2.48.2/./gobject/gsignal.c:3486: signal name 'selection_changed' is invalid for instance '0x7f5a2d2db830' of type 'MaiAtkType13b'
[Child 7175] ###!!! ABORT: Aborting on channel error.: file /build/firefox-z5GTBX/firefox-51.0.1+build2/ipc/glue/MessageChannel.cpp, line 2056
[Child 7175] ###!!! ABORT: Aborting on channel error.: file /build/firefox-z5GTBX/firefox-51.0.1+build2/ipc/glue/MessageChannel.cpp, line 2056

###!!! [Child][MessageChannel] Error: (msgtype=0x1040003,name=PTexture::Msg_Destroy) Channel error: cannot send/recv


###!!! [Child][MessageChannel] Error: (msgtype=0x1040003,name=PTexture::Msg_Destroy) Channel error: cannot send/recv


###!!! [Child][MessageChannel] Error: (msgtype=0x420003,name=PCompositable::Msg_Destroy) Channel error: cannot send/recv


###!!! [Child][MessageChannel] Error: (msgtype=0x1040003,name=PTexture::Msg_Destroy) Channel error: cannot send/recv


###!!! [Child][MessageChannel] Error: (msgtype=0x1040003,name=PTexture::Msg_Destroy) Channel error: cannot send/recv
```

I'm running on Ubuntu 16.04. I tried both geckodriver v14 (x64) and geckodriver v13 (x64), none worked. Also tried performing a clean Firefox install (renamed .mozilla, apt-get --purge, etc) but that didn't work as well.

**Comment by parislarkins** [comment]
Thanks for the logs!

The problem is that, as I outlined above, your account was successfully created however the browser was not redirected to the signup complete page. If I set the /sign-up page to be a sign of success, it will have the side effect of a lot of false-positives in case the username is legitimately taken. What I'm thinking is, because it seems people either get this error 100% of the time, or 0%, that I could have a setting for those with this problem to ignore the lack of redirect and mark it as a success. 

I suppose another option could be to log into the email and check if an email arrived too.

**Comment by ghost** [comment]
@novskey Thank you very much for replying. Ignoring the redirect would solve the issue for me since, as you stated, the accounts are being successfully created. Checking for the email arrival would also do the trick since I think that despite the fact that I'm getting account confirmation emails, they are not being auto verified (since the message is still in the inbox and not in Trash).

**Comment by DennyLoko** [comment]
I'm experiencing the similar issue, but my accounts are not being created. I've checked for the messages on inbox, trash and spam, but I received none.

**Comment by DennyLoko** [comment]
I've digger into my problem, and I found that my issue is not related to this, but regarding the password strength. Looks like the special character of the password can't be `.`.

**Comment by parislarkins** [comment]
Ahh. There's a list of allowed characters on the PTC sign up page

**Comment by ashleykleynhans** [comment]
I am also having this problem, I checked my email and there don't seem to be any mails coming through so it appears that the accounts aren't being created at all, even with passwords that don't contain a `.`

**Comment by parislarkins** [comment]
Could you paste a log for this issue?

**Comment by ashleykleynhans** [comment]
@novskey It was my mistake, I accidentally entered the Pokemon Go site key instead of my 2captcha key.  Would it be possible to add some kind of error checks for incorrect 2captcha keys because the error logs from Pallet Town didn't indicate that my key was wrong at all.  I would have been able to correct the issue very quickly if I knew my 2captcha key was incorrect.

**Comment by parislarkins** [comment]
Yeah absolutely :) There's a feature (currently disabled) that checks your 2captcha balance before account creation and displayed it, then asked if you wanted to proceed. This would pick up any errors in 2captcha keys. The only problem is it will need some reworking as ever since it was running in multiple threads its a bit more complicated to run and wait for you to click proceed. I'll definitely be working on it when I have some time, busy with uni at the moment unfortunately.

**Comment by altor90** [comment]
I have similar problem. Pallet starts to make an account and suddenly stops after manually recaptcha. It looks like e-mails with "+" do not work - when I do it by myself on PTC, without Pallet, there is an error that e-mail (with data and "+" the same like with Pallet) is filled wrong. Maybe it do not work anymore?

With Pallet:

[Main Thread]: Attempting to create user [user]:[password]. Opening browser...
[Main Thread]: Proxy type: 
[Main Thread]: No 2captcha key
[Main Thread]: trying to execute workaround script
[Main Thread]: done executing workaround script, submitting dob
[Main Thread]: dob submitted
[Main Thread]: Step 2: Entering account details
[Main Thread]: ht tps://club.pokemon.com/us/pokemon-trainer-club/parents/sign-up
[Main Thread]: ht tps://club.pokemon.com/us/pokemon-trainer-club/parents/sign-up
[Main Thread]: You did not pass a 2captcha key. Please solve the captcha manually.
[Main Thread]: Waiting on captcha
[Main Thread]: Captcha successful. Sleeping for 1 second...
[Main Thread]: trying to submit
[Main Thread]: submitted
[Main Thread]: trying to validate response
[RESPONSE_VALIDATOR]: ht tps://club.pokemon.com/us/pokemon-trainer-club/parents/sign-up
[RESPONSE_VALIDATOR]: Username already in use
[Main Thread]: Failed to create user: [user]...
[Main Thread]: threw failed to create user exception, terminate

Please, help!

**Comment by parislarkins** [comment]
Are you using a hotmail address? PTC patched hotmail + trick recently. Try zoho or googlemail

**Comment by altor90** [comment]
Yes, thank you!
